version: "2"

x-app: &base
    build: .
    volumes:
      - .:/src/app
      - /home/wardormeur/go/pkg/mod:/go/src
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=curations
      - POSTGRES_USER=curator
      - POSTGRES_PASSWORD=publicIAM
    working_dir: /src/app
    command: reflex -r '(\.go$$|go\.mod)' -s go run .
    depends_on:
      - db

services:
  app:
    <<: *base
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=curator
      - POSTGRES_DB=curations
      - POSTGRES_PASSWORD=publicIAM
    ports:
      - 5432:5432
